#!/bin/bash

set -e

directory=$1

cd "$directory"
echo "Pulling changes from $BACKUP_BRANCH_NAME..."
if git fetch "$GIT_ORIGIN_NAME" "$BACKUP_BRANCH_NAME" &>/dev/null; then
	git reset --soft "$GIT_ORIGIN_NAME/$BACKUP_BRANCH_NAME"
fi
