name: "Build Docker image and publish to GHCR"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=ref,event=push
      - name: Build
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
      - name: Test
        env:
          IMAGE: ghcr.io/${{ github.repository }}
          TAG: ${{ steps.meta.outputs.tags }}
        run: ./run_tests.sh "$IMAGE:$TAG"
      - name: Push as latest
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE: ghcr.io/${{ github.repository }}
          SOURCE_TAG: ${{ steps.meta.outputs.tags }}
          DEST_TAG: latest
        run: |
          docker pull "$IMAGE:$SOURCE_TAG"
          docker tag "$IMAGE:$SOURCE_TAG" "$IMAGE:$DEST_TAG"
          docker push "$IMAGE:$DEST_TAG"