name: "Build Docker image and publish to GHCR"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha
      - name: Build
        uses: docker/build-push-action@v6.13.0
        with:
          context: ./src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
      - name: Test
        env:
          IMAGE: ${{ steps.meta.outputs.tags }}
        run: ./run_tests.sh "$IMAGE"
      - name: Push to latest
        if: github.ref == 'refs/heads/main'
        env:
          SOURCE_IMAGE: ${{ steps.meta.outputs.tags }}
        run: |
          DEST_IMAGE=$(echo "$SOURCE_IMAGE" | sed 's/:.*$/:latest/')
          echo "Pushing $SOURCE_IMAGE to $DEST_IMAGE"
          docker tag "$SOURCE_IMAGE" "$DEST_IMAGE"
          docker push "$DEST_IMAGE"